"""
build_endex_sequences.py
==========================
One-off script: builds 5-touch multichannel cadences (touches 2-5; touch 1
is the hook already generated by generate_endex_hooks.py) for every OK,
non-held-back Endex hook, via cadence_builder.py. Mirrors the QuadSci
Sequences tab build.

Demo/one-off script — not part of the reusable glassbox engine.
"""

import sys
from pathlib import Path

from dotenv import load_dotenv

BASE_DIR = Path(__file__).parent
ORACLE_DIR = BASE_DIR / "oracle_intent_engine"
sys.path.insert(0, str(ORACLE_DIR))
load_dotenv(ORACLE_DIR / ".env")
load_dotenv(BASE_DIR / "lead_enrichment_engine" / ".env")

from src import database as db
from src.cadence_builder import build_sequence

COMPANIES = [
    'Ares Management', 'Citi', 'BMO Capital Markets', 'UBS',
    'Oppenheimer & Co. Inc.', 'Santander US',
    'Houlihan Lokey', 'Raymond James', 'Jefferies',
    'Cohen & Company Capital Markets', 'Brown Advisory', 'Alpha Alternatives',
]

PRODUCT_CONTEXT = """
Endex — Excel-native AI agent for finance. Builds DCF and three-statement
models directly inside Excel, with integrated citations for auditable
outputs, pulling from SEC filings, Capital IQ, and FactSet. Custom-built
LLMs engineered for finance, not a generic wrapper.
""".strip()


def main():
    db.init_db()
    all_hooks = db.get_recent_campaign_hooks(limit=100)
    hooks = [h for h in all_hooks if h.get("ok") and not h.get("hold_back")
             and h.get("company_name") in COMPANIES]
    # one hook per company — the most recent (list is already created_at DESC)
    seen = set()
    target_hooks = []
    for h in hooks:
        if h["company_name"] in seen:
            continue
        seen.add(h["company_name"])
        target_hooks.append(h)

    print(f"Building sequences for {len(target_hooks)} hooks...")
    ok_count = 0
    for h in target_hooks:
        hook_dict = {
            "contact_name": h["contact_name"],
            "company": h["company_name"],
            "title": h["contact_title"],
            "subject": h["subject"],
            "body": h["body"],
            "angle": h["angle"],
            "ok": h["ok"],
        }
        seq = build_sequence(hook_dict, product_context=PRODUCT_CONTEXT)
        if seq.get("ok"):
            db.save_campaign_touches(h["id"], seq["touches"])
            ok_count += 1
            print(f"[OK] {h['company_name']} -> {h['contact_name']}: {len(seq['touches'])} touches")
        else:
            print(f"[FAILED] {h['company_name']}: {seq.get('error')}")

    print(f"\n{ok_count}/{len(target_hooks)} sequences built successfully")


if __name__ == "__main__":
    main()
