"""
config.py  (intent_engine)
==================================
Central configuration loader for the intent detection engine.

PURPOSE:
  Single source of truth for all API keys, database connection details, rate-limit
  settings, and the seed search queries that drive the job-board scrapers.
  All secrets come from intent_engine/.env — never hardcoded.

  The engine is taxonomy-driven, not tied to one vendor: the active product/phase
  taxonomy is loaded at runtime from the `product_taxonomy` DB table (falling back
  to icp_profiles/*.yaml — see phase_classifier.py). QUERIES_BY_PRODUCT below is
  handcrafted seed data for products in the default taxonomy; any product added to
  the taxonomy without a handcrafted entry gets queries auto-generated by
  generate_queries_for_product(). Individual campaigns (e.g. icp_profiles/quadsci.yaml,
  endex.yaml) supply their own keywords entirely and don't touch this file.

HOW IT FITS IN THE SYSTEM:
  Imported at the top of almost every intent_engine module.
  unified_app.py loads the .env file BEFORE importing this module, so any env vars
  set by unified_app.py are already visible when config attributes are first read.

KEY ATTRIBUTES:
  DB_*                  — PostgreSQL connection details
  APOLLO_API_KEY        — used by apollo_enrichment.py (X-Api-Key header, NOT Bearer)
  ZEROBOUNCE_API_KEY    — used by apollo_enrichment.py for email validation
  QUERIES_BY_PRODUCT    — handcrafted job-board queries for the default taxonomy's products
  JDE_MANUFACTURING_QUERIES — extra queries for the JDE Manufacturing Focus mode
  NEWS_QUERIES          — queries consumed by news_signal.py
  MAX_PAGES             — per-source page cap (prevents runaway scraping costs)
  SCAN_DELAY_MIN/MAX    — seconds to sleep between HTTP requests (politeness tier)

DEPENDENCIES:
  - python-dotenv (reads intent_engine/.env)
  - No DB or API calls occur at import time
"""

import os
from dotenv import load_dotenv

load_dotenv()

DB_HOST = os.getenv("DB_HOST", "localhost").strip()
DB_PORT = os.getenv("DB_PORT", "5432").strip()
DB_NAME = os.getenv("DB_NAME", "Inoapps-Data-DB").strip()
DB_USER = os.getenv("DB_USER", "postgres").strip()
DB_PASSWORD = os.getenv("DB_PASSWORD", "").strip()

NEWSAPI_KEY = os.getenv("NEWSAPI_KEY", "").strip()
BING_NEWS_KEY = os.getenv("BING_NEWS_KEY", "").strip()

# Hunter.io — free tier: 25 domain searches/month → decision-maker contacts
# Get key at: https://hunter.io/api (free signup)
HUNTER_API_KEY = os.getenv("HUNTER_API_KEY", "").strip()

# Apollo.io — people search + email reveal
# Get key at: https://developer.apollo.io/
APOLLO_API_KEY = os.getenv("APOLLO_API_KEY", "").strip()

# ZeroBounce — email validation (1 credit per email)
# Get key at: https://app.zerobounce.net/
ZEROBOUNCE_API_KEY = os.getenv("ZEROBOUNCE_API_KEY", "").strip()

# ZoomInfo — alternative contact-discovery provider (enterprise API)
# Auth: POST /authenticate with username+password → JWT (60 min)
ZOOMINFO_USERNAME = os.getenv("ZOOMINFO_USERNAME", "").strip()
ZOOMINFO_PASSWORD = os.getenv("ZOOMINFO_PASSWORD", "").strip()

# Adzuna — free job board API (250 calls/day free)
# Register at: https://developer.adzuna.com/
ADZUNA_APP_ID  = os.getenv("ADZUNA_APP_ID",  "").strip()
ADZUNA_APP_KEY = os.getenv("ADZUNA_APP_KEY", "").strip()

# ScrapeGraphAI — set SCRAPEGRAPH_MODEL to enable LLM scraping
# Free/local:  SCRAPEGRAPH_MODEL=ollama/llama3.1
# Paid/better: SCRAPEGRAPH_MODEL=anthropic/claude-haiku-4-5-20251001  (set SCRAPEGRAPH_API_KEY too)
SCRAPEGRAPH_MODEL     = os.getenv("SCRAPEGRAPH_MODEL", "").strip()
SCRAPEGRAPH_API_KEY   = os.getenv("SCRAPEGRAPH_API_KEY", "").strip()
SCRAPEGRAPH_OLLAMA_URL = os.getenv("SCRAPEGRAPH_OLLAMA_URL", "http://localhost:11434").strip()

# Ollama local LLM — company extraction fallback (free, runs locally)
# Install Ollama from ollama.ai, then: ollama pull llama3.2
OLLAMA_URL   = os.getenv("OLLAMA_URL",   "http://localhost:11434").strip()
OLLAMA_MODEL = os.getenv("OLLAMA_MODEL", "llama3.2").strip()

SCAN_DELAY_MIN = float(os.getenv("SCAN_DELAY_MIN", "2"))
SCAN_DELAY_MAX = float(os.getenv("SCAN_DELAY_MAX", "6"))
MAX_PAGES = int(os.getenv("MAX_PAGES", "3"))

# 280K contacts CSV — used to match detected companies with known contacts
CONTACTS_CSV_PATH = os.getenv(
    "CONTACTS_CSV_PATH",
    r"C:\Users\sidhartha\OneDrive\Desktop\280K\ALL_CONTACTS_CONSOLIDATED.csv"
)


# agentic_harvester_signal.py watch list — comma-separated URLs, e.g. a
# procurement portal's open-tenders page or an Oracle partner directory.
# Adding a new source to watch is editing this list, not writing a scraper.
AGENTIC_HARVESTER_URLS = [
    u.strip() for u in os.getenv("AGENTIC_HARVESTER_URLS", "").split(",") if u.strip()
]

# ── ATS signal board registry (ats_signal.py) ────────────────────────────────
# Companies publish their own open roles as clean public JSON on these ATS
# platforms — highest signal-to-noise, ~0% block rate. A company hiring a
# "Salesforce Developer" is a first-party confirmed-customer signal.
#
# Registry format (env override): ATS_BOARDS="greenhouse:stripe,ashby:openai,lever:mistral"
# Adding a company to watch = one entry here, not a new scraper.
_DEFAULT_ATS_BOARDS = [
    # Verified live (Jul 2026). Mix of ATS types so coverage survives any one
    # platform 404'ing for a given company.
    {"ats": "greenhouse", "token": "stripe"},
    {"ats": "greenhouse", "token": "databricks"},
    {"ats": "greenhouse", "token": "gitlab"},
    {"ats": "greenhouse", "token": "figma"},
    {"ats": "greenhouse", "token": "anthropic"},
    {"ats": "ashby",      "token": "openai"},
    {"ats": "ashby",      "token": "Ramp"},
    {"ats": "ashby",      "token": "Notion"},
    {"ats": "lever",      "token": "mistral"},
    {"ats": "lever",      "token": "spotify"},
]

def _parse_ats_boards(env_val: str) -> list[dict]:
    boards = []
    for entry in env_val.split(","):
        entry = entry.strip()
        if ":" in entry:
            ats, token = entry.split(":", 1)
            if ats.strip() and token.strip():
                boards.append({"ats": ats.strip(), "token": token.strip()})
    return boards

_ats_env = os.getenv("ATS_BOARDS", "").strip()
ATS_BOARDS = _parse_ats_boards(_ats_env) if _ats_env else list(_DEFAULT_ATS_BOARDS)

# Default title-match only — a body mention ("CRM hygiene" in an AE post) is
# mostly noise; a title match ("Salesforce Administrator") is a real operating
# signal. Live test: 1,982 body matches vs 7 title matches — the 7 were the
# actual buyers. Flip to include weak body matches at the cost of noise.
ATS_INCLUDE_BODY_MATCHES = os.getenv("ATS_INCLUDE_BODY_MATCHES", "false").lower() in ("1", "true", "yes")
ATS_MAX_JOBS_PER_BOARD = int(os.getenv("ATS_MAX_JOBS_PER_BOARD", "300"))

# Intent keywords for the default (non-campaign) scan — job titles that prove
# a company OPERATES a product from the default taxonomy internally. Campaign
# scans pass their own campaign_keywords instead.
ATS_DEFAULT_INTENT_KEYWORDS = [
    "Oracle", "NetSuite", "JD Edwards", "JDE", "PeopleSoft", "Hyperion",
    "Oracle Cloud", "Oracle ERP", "Oracle EBS", "E-Business Suite", "Fusion",
]

# ── Role suffixes used by the auto-generator for new taxonomy products ────────
# When a product is added to the taxonomy but has no entry in QUERIES_BY_PRODUCT,
# these suffixes are crossed with the canonical name and multi-word aliases to
# produce search queries automatically.
_ROLE_SUFFIXES = [
    "consultant",
    "implementation consultant",
    "functional consultant",
    "technical consultant",
    "administrator",
    "project manager",
    "developer",
    "upgrade",
    "implementation",
    "migration consultant",
]


def generate_queries_for_product(canonical_name: str, aliases: list[str]) -> list[str]:
    """
    Auto-generate job-board search queries for a taxonomy product that has no
    handcrafted entry in QUERIES_BY_PRODUCT.

    Strategy:
      - canonical_name × _ROLE_SUFFIXES  → core queries
      - aliases with 3+ words            → used directly (already search-query quality)
      - aliases with 2 words             → paired with top 3 suffixes
    """
    seen: set[str] = set()
    queries: list[str] = []

    def _add(q: str) -> None:
        q = q.strip()
        if q and q not in seen:
            seen.add(q)
            queries.append(q)

    for suffix in _ROLE_SUFFIXES:
        _add(f"{canonical_name} {suffix}")

    for alias in aliases:
        words = alias.strip().split()
        titled = " ".join(w.capitalize() for w in words)
        if len(words) >= 3:
            _add(titled)
        elif len(words) == 2:
            for suffix in ("consultant", "implementation", "administrator"):
                _add(f"{titled} {suffix}")

    return queries


# ── Proven queries per canonical product name ─────────────────────────────────
# Pipeline reads only the queries whose product is active in the taxonomy.
# When a new product is added to the taxonomy AND is not listed here,
# generate_queries_for_product() is called automatically.
QUERIES_BY_PRODUCT: dict[str, list[str]] = {
    # ── JD Edwards ────────────────────────────────────────────────────
    "JD Edwards": [
        "JD Edwards consultant",
        "JDE EnterpriseOne implementation",
        "JD Edwards ERP upgrade",
        "JDE technical developer",
        "JD Edwards functional consultant",
        "JDE CNC administrator",
        "JD Edwards project manager",
        "JDE EnterpriseOne support analyst",
        "JDE system administrator",
        "JDE basis administrator",
        "JDE solution architect",
        "JDE orchestrator developer",
        "JDE security administrator",
        "JDE report developer",
        "JD Edwards business analyst",
        # High-yield confirmed (tested May 2026)
        "JD Edwards 9.2 upgrade",
        "JD Edwards upgrade project manager",
        # Migration
        "JD Edwards migration Oracle Cloud",
        "JDE to Oracle Cloud migration",
        "JDE EnterpriseOne cloud migration",
        # Verticals — manufacturing
        "JD Edwards manufacturing consultant",
        "JDE MRP work orders bill of materials",
        "JD Edwards shop floor manufacturing ERP",
        "JDE discrete manufacturing implementation",
        # Verticals — construction & home building
        "JD Edwards construction ERP consultant",
        "JDE job costing homebuilder",
        "JD Edwards EnterpriseOne construction",
        "JDE land development procurement",
        # Verticals — energy & utilities
        "JD Edwards energy oil gas ERP",
        "JDE EnterpriseOne utilities consultant",
        # Verticals — agriculture & distribution
        "JD Edwards agriculture ERP consultant",
        "JDE food beverage agribusiness implementation",
        "JD Edwards distribution consultant",
        "JDE wholesale distribution implementation",
    ],
    # ── JD Edwards World ─────────────────────────────────────────────
    "JD Edwards World": [
        "JD Edwards World consultant",
        "JDE World administrator",
        "JD Edwards World AS400 administrator",
        "JDE World upgrade EnterpriseOne",
        "JD Edwards World to EnterpriseOne migration",
        "JDE World technical developer",
        "JD Edwards World support analyst",
    ],
    # ── Oracle Cloud ERP (Fusion) ─────────────────────────────────────
    "Oracle Cloud ERP": [
        "Oracle Cloud ERP consultant",
        "Oracle Fusion ERP implementation",
        "Oracle Financials Cloud consultant",
        "Oracle ERP Cloud migration",
        "Oracle Fusion Cloud implementation manager",
        "Oracle Financials Cloud project manager",
        "Oracle Cloud ERP project manager",
        "Oracle Fusion ERP developer",
        "Oracle Cloud ERP functional consultant",
        "Oracle Fusion financials administrator",
    ],
    # ── Oracle E-Business Suite ───────────────────────────────────────
    "Oracle E-Business Suite": [
        "Oracle E-Business Suite consultant",
        "Oracle EBS implementation",
        "Oracle EBS R12 upgrade",
        "Oracle EBS functional consultant",
        "Oracle EBS technical developer",
        "Oracle E-Business Suite project manager",
        "Oracle EBS migration cloud",
        "Oracle EBS financials consultant",
        "Oracle EBS HRMS consultant",
        "Oracle EBS supply chain consultant",
        "Oracle Apps DBA",
        "Oracle EBS database administrator",
    ],
    # ── Oracle PeopleSoft ─────────────────────────────────────────────
    "Oracle PeopleSoft": [
        "Oracle PeopleSoft consultant",
        "PeopleSoft HCM implementation",
        "PeopleSoft Financials consultant",
        "PeopleSoft FSCM consultant",
        "PeopleSoft technical developer",
        "PeopleSoft upgrade consultant",
        "PeopleSoft to Oracle Cloud migration",
        "PeopleSoft campus solutions consultant",
        "PeopleSoft administrator",
        "PeopleSoft project manager",
    ],
    # ── Oracle NetSuite ───────────────────────────────────────────────
    "Oracle NetSuite": [
        "NetSuite implementation consultant",
        "Oracle NetSuite ERP",
        "NetSuite administrator",
        "NetSuite ERP project manager",
        "NetSuite developer",
        "NetSuite functional consultant",
        "NetSuite SuiteScript developer",
        "NetSuite OneWorld implementation",
        "NetSuite ERP migration",
    ],
    # ── Oracle HCM Cloud ─────────────────────────────────────────────
    "Oracle HCM Cloud": [
        "Oracle HCM Cloud consultant",
        "Oracle Fusion HCM implementation",
        "Oracle Global HR Cloud consultant",
        "Oracle HCM Cloud project manager",
        "Oracle Payroll Cloud consultant",
        "Oracle HCM Cloud administrator",
        "Oracle HCM Cloud functional consultant",
        "Oracle Recruiting Cloud consultant",
        "Oracle Learning Cloud consultant",
    ],
    # ── Oracle SCM Cloud ─────────────────────────────────────────────
    "Oracle SCM Cloud": [
        "Oracle SCM Cloud consultant",
        "Oracle Supply Chain Cloud implementation",
        "Oracle Procurement Cloud consultant",
        "Oracle Manufacturing Cloud consultant",
        "Oracle SCM Cloud project manager",
        "Oracle Order Management Cloud consultant",
        "Oracle Inventory Cloud consultant",
        "Oracle OTM consultant",
    ],
}

# ── JDE Manufacturing Focus queries ─────────────────────────────────────────
# Used when "JDE Manufacturing Focus" is enabled in Engine Control.
# These target manufacturing end-users specifically — not staffing/consulting firms.
JDE_MANUFACTURING_QUERIES = [
    # Core JDE manufacturing roles (end-user companies hiring these = implementing JDE)
    "JD Edwards EnterpriseOne manufacturing ERP manager",
    "JDE manufacturing systems administrator",
    "JD Edwards production planning MRP manager",
    "JDE shop floor control work orders director",
    "JD Edwards discrete manufacturing project manager",
    "JDE process manufacturing implementation lead",
    "JD Edwards bill of materials routing engineer",
    "JDE demand planning supply chain manager manufacturing",
    "JD Edwards quality management manufacturing director",
    # Industry verticals — manufacturing companies hiring JDE roles
    "JD Edwards automotive manufacturing ERP",
    "JDE aerospace defense ERP implementation",
    "JD Edwards industrial equipment manufacturer ERP",
    "JDE food beverage manufacturing ERP manager",
    "JD Edwards chemical manufacturing ERP consultant",
    "JDE electronics manufacturer ERP systems",
    "JD Edwards metal fabrication ERP project",
    "JDE plastics rubber manufacturing systems manager",
    "JD Edwards packaging manufacturer ERP",
    "JDE pharmaceutical manufacturing ERP systems",
    # Migration signals — manufacturing companies moving off legacy
    "JD Edwards Oracle Cloud migration manufacturing director",
    "JDE EnterpriseOne upgrade manufacturing company",
    "migrating JDE manufacturing Oracle Cloud project manager",
    "JD Edwards to Oracle Cloud ERP manufacturing",
    # Construction & home building (separate from general JDE)
    "JD Edwards construction job costing project director",
    "JDE EnterpriseOne homebuilder land development",
    "JD Edwards construction procurement manager",
]

NEWS_QUERIES = [
    # Go-live / completion announcements
    "Oracle Cloud ERP go live 2024",
    "Oracle Fusion ERP implementation go live",
    "company selects Oracle Cloud ERP",
    "Oracle Cloud ERP digital transformation announcement",
    "goes live Oracle Cloud ERP enterprise",
    "Oracle ERP implementation completed",
    # HCM
    "Oracle HCM Cloud deployment announcement",
    "Oracle Fusion HCM go live",
    "company implements Oracle HCM Cloud",
    # SCM / EPM
    "Oracle SCM Cloud implementation announcement",
    "Oracle EPM Cloud go live finance",
    "Oracle Planning Cloud implementation",
    # NetSuite
    "NetSuite ERP implementation go live",
    "company migrates to NetSuite ERP",
    "NetSuite cloud ERP announcement",
    # OCI / Database
    "Oracle OCI cloud migration announcement",
    "migrates to Oracle Cloud Infrastructure",
    "Oracle Autonomous Database implementation",
    # Press release / partner signals
    "selects Oracle Cloud ERP announcement press release",
    "Oracle ERP transformation press release 2024",
    "implements Oracle Fusion Cloud applications",
    "Oracle partner implementation success 2024",
    # Industry-specific
    "manufacturing Oracle Cloud ERP implementation",
    "retail Oracle Cloud ERP go live",
    "financial services Oracle Cloud ERP",
    "healthcare Oracle Cloud ERP implementation",
    "public sector Oracle Cloud ERP",
    # Competitive migration
    "SAP to Oracle Cloud migration",
    "migrating from SAP to Oracle",
    "Oracle replaces SAP ERP",
    # JD Edwards news
    "JD Edwards implementation go live",
    "company upgrades JD Edwards EnterpriseOne",
    "JDE ERP transformation announcement",
    "migrating from JD Edwards to Oracle Cloud",
    "JD Edwards digital transformation",
    "JDE EnterpriseOne upgrade announcement",
    "company selects JD Edwards ERP",
    "JDE to Oracle Cloud migration",
    # Oracle E-Business Suite (EBS) news — large legacy install base
    "Oracle E-Business Suite go live implementation",
    "Oracle EBS upgrade announcement",
    "company migrates from Oracle EBS to cloud",
    "Oracle EBS R12 implementation go live",
    "Oracle EBS modernization cloud migration",
    "Oracle EBS digital transformation announcement",
    # PeopleSoft news — HR/Finance, public sector and higher education
    "Oracle PeopleSoft upgrade implementation",
    "PeopleSoft HCM go live announcement",
    "company upgrades PeopleSoft ERP",
    "PeopleSoft to Oracle Cloud migration announcement",
    "PeopleSoft campus solutions implementation",
    "university PeopleSoft implementation go live",
    # Siebel CRM news — telco, insurance, financial services
    "Oracle Siebel CRM upgrade implementation",
    "Siebel to Oracle CX Cloud migration",
    "company replaces Siebel CRM Oracle",
    # Hyperion news — CFO / finance office
    "Oracle Hyperion implementation go live",
    "Oracle Hyperion upgrade announcement",
    "company deploys Oracle Hyperion EPM",
    # Oracle Analytics / BI news
    "Oracle Analytics Cloud implementation",
    "Oracle BI implementation announcement",
    "Oracle Analytics go live company",
]
